# Generated by Django 3.2.2 on 2021-05-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('revies', models.TextField(max_length=300)),
                ('rating', models.IntegerField(verbose_name=5)),
            ],
        ),
    ]
